ravtovich_blog_homepage:
    path:     /
    defaults: { _controller: "RavtovichBlogBundle:Blog:index" }
ravtovich_blog_about:
    path:   /about
    defaults: { _controller: "RavtovichBlogBundle:Blog:about" }
    requirements:
    methods:  GET
ravtovich_blog_contact:
     path:  /contact
     defaults: { _controller: "RavtovichBlogBundle:Blog:contact" }
     requirements:
         methods:  GET|POST
ravtovich_blog_show:
    path:  /{id}
    defaults: { _controller: "RavtovichBlogBundle:Post:show" }
    requirements:
        methods:  GET
        id: \d+

ravtovich_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: "RavtovichBlogBundle:Comment:create" }
    requirements:
        methods:  POST
        blog_id: \d+
