ravtovich_blog_homepage:
    path:     /
    defaults: { _controller: "RavtovichBlogBundle:Post:index" }
ravtovich_blog_about:
    path:   /about
    defaults: { _controller: "RavtovichBlogBundle:Post:about" }
    requirements:
    methods:  GET
ravtovich_blog_contact:
     path:  /contact
     defaults: { _controller: "RavtovichBlogBundle:Post:contact" }
     requirements:
         methods:  GET|POST
