ravtovich_blog:
    resource: "@RavtovichBlogBundle/Resources/config/routing.yml"
    prefix:   /

RavtovichBlogBundle_homepage:
                          path:     /
                          defaults: { _controller: "RavtovichBlogBundle:Page:index" }
                          requirements:
                               methods:  GET

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin