admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

ravtovich_blog_homepage:
    path:     /
    controller: App\Controller\BlogController::indexAction
ravtovich_blog_about:
    path:   /about
    controller: App\Controller\BlogController::aboutAction
    requirements:
    methods:  GET
ravtovich_blog_contact:
     path:  /contact
     defaults: { _controller: "RavtovichBlogBundle:Blog:contact" }
     requirements:
         methods:  GET|POST
ravtovich_blog_show:
    path:  /{id}/{slug}
    controller: App\Controller\PostController::showAction
    defaults: {
      comments: true
      }
    requirements:
        methods:  GET
        id: \d+

ravtovich_comment_create:
    path:  /comment/{post_id}
    controller: App\Controller\CommentController::createAction
    requirements:
        methods:  POST
        blog_id: \d+


